[versions]
activityCompose = "1.11.0"
androidxComposeMaterial3 = "1.3.0"
androidxComposeMaterial3Adaptive = "1.1.0-rc01"
androidxComposeMaterial3AdaptiveNavigation3 = "1.3.0-alpha04"
agp = "8.12.3"
annotationJvm = "1.9.1"
androidTools = "31.13.1"
coil = "2.6.0"
composeBom = "2024.09.00"
composeCompiler = "2.0.21"
converterGson = "2.9.0"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
hiltnavigation = "1.2.0"
hiltAndroid = "2.57.2"
hiltNavigationCompose = "1.1.0"
javaXInject = "1"
junit = "4.13.2"
junitVersion = "1.3.0"
koltinxSerializationJson = "1.6.3"
kotlin = "2.1.10"
kotlinxCoroutines = "1.8.1"
ksp = "2.1.10-1.0.29"
lifecycleRuntimeKtx = "2.9.4"
loggingInterceptor = "4.9.2"
loggingInterceptorVersion = "4.12.0"
mockk = "1.14.9"
navigation = "2.9.6"
retrofit = "2.11.0"
retrofitKotlinxSerializationJson = "1.0.0"
timber = "5.0.1"
truth = "1.4.4"
turbine = "1.2.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-navigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3",version.ref="androidxComposeMaterial3AdaptiveNavigation3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-navigation = { group = "androidx.navigation",name="navigation-compose",version.ref = "navigation"}
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }


retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }


hilt-navigation = {group="androidx.hilt",name="hilt-navigation-compose",version.ref = "hiltnavigation"}
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hiltAndroid" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "koltinxSerializationJson" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
javax-inject = {group="javax.inject",name="javax.inject",version.ref="javaXInject"}
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }


android-gradleApiPlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }


[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = {id="com.google.devtools.ksp",version.ref="ksp"}
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }


#plugins defined by ricky morty world

rmworld-android-application = { id = "com.rmworld.android.application" }
rmworld-android-library = { id = "com.rmworld.android.library" }
rmworld-android-library-compose = {id = "com.rmworld.android.library.compose"}
rmworld-hilt = {id="com.rmworld.hilt"}
